### ISSUE TITLE
localStorage.json error on startup

### ISSUE THREAD

**Issue by dapersonmgn** [Bibliofile/Blockheads-MessageBot#45]
**Before reporting an issue please make sure the following boxes are checked:**

## If using the node version:
- [x] Node v6.10.0 or later (run `node -v`)
- [x] Bot's code up to date (run `npm update blockheads-messagebot`)

Also please fill in the following information:
Your node version: v7.8.0
Your OS: Windows 10
Steps to reproduce: Open up the bot. There's an error message about localStorage.json
```
Error importing localStorage.json SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\User\Blockheads-MessageBot\build\libraries\storage\index.js:38:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\User\Blockheads-MessageBot\build\index-cli.js:47:17)

```

**Comment by dapersonmgn** [comment]
Just checked my config file. My localStorage.json file is 
[object Object]
